In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import os 
import sys

In [2]:
ROOT_W = os.path.abspath("..")

os.chdir(ROOT_W)
sys.path.insert(0, ROOT_W)

In [3]:
# Load scripts
from src.local_config import *

In [6]:
# Open files 
prices = pd.read_parquet(ROOT_W / "data/prices.parquet")
sp_500_c = prices = pd.read_parquet(ROOT_W / "data/sp500_constituents.parquet")
sp_400_c = pd.read_parquet(ROOT_W / "data/sp400_constituents.parquet")
all_data = pd.read_parquet(ROOT_W / "data/all_data.parquet")
cheapness_scores = pd.read_parquet(ROOT_W / "data/cheapness_scores.parquet")
piotrosky = pd.read_parquet(ROOT_W / "data/piotrosky.parquet")
earnings_calendar = pd.read_parquet(ROOT_W / "data/earnings_calendar.parquet")
short_int_trans = pd.read_parquet(ROOT_W / "data/short_interest_transfo.parquet")
regime = pd.read_parquet(ROOT_W / "data/regime.parquet")
gics = pd.read_parquet(ROOT_W / "data/gics_info.parquet")
benchmark = pd.read_parquet(ROOT_W / "data/sp500_tr.parquet")

rolling_upgrade = pd.read_csv(ROOT_W / "data/rolling_scores_upgrade.csv")
rolling_downgrade = pd.read_csv(ROOT_W / "data/rolling_scores_downgrade.csv")

# Return Objects

Overnight Return:
$$
r_{ON,t}=(\frac{\text{Open}_t}{\text{Close}_{t-1}})-1
$$

Intraday Return:
$$
r_{ID,t}=(\frac{\text{Open}_t}{\text{Close}_{t}})-1
$$

Close-to-Close Return:
$$
(1+r_{ON,t})\times(1+r_{ID,t})-1=(\frac{Close_t}{Close_{t-1}})-1
$$

In [16]:
all_data.head()

,stock_id,date,piot_norm,dsi,dtcn,ddtcn,short_interest,asset_turnover_ratio,current_liabilities,ev_to_ebit,...,gics_industry,gics_subindustry,open,high,low,close,close_split_adj,volume,market_cap,industry_return
0,31,2000-01-10,0.0,NaN,NaN,NaN,NaN,0.045338,NaN,14.81990,...,401010,40101015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,66,2000-01-10,0.0,NaN,NaN,NaN,NaN,0.952662,2.593000e+09,16.96610,...,201010,20101010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,775,2000-01-10,0.0,NaN,NaN,NaN,NaN,0.445783,5.140000e+05,NaN,...,352010,35201010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,153,2000-01-11,0.0,NaN,NaN,NaN,NaN,0.867936,3.462000e+09,10.84250,...,151030,15103020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,221,2000-01-11,0.0,NaN,NaN,NaN,NaN,1.568870,3.335320e+08,3.83609,...,252010,25201030,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
prices.head()

  ticker   add_date remove_date
0      A 2000-06-05         NaT
1   AABA 1999-12-08  2017-06-19
2    AAL 1996-01-02  1997-01-15
3    AAL 2015-03-23  2024-09-23
4  AAMRQ 1996-01-02  2003-03-14

In [15]:
earnings_calendar.head()

,stock_id,reporting_date,strat_trading_date,reporting_time,before_after_market,period,period_end_date
0,1,2014-02-27,2014-02-26,0 days 13:30:00,before,FY2013Q4,2013-12-31
1,1,2014-05-09,2014-05-08,0 days 12:30:00,before,FY2014Q1,2014-03-31
2,1,2014-08-01,2014-07-31,0 days 12:30:00,before,FY2014Q2,2014-06-30
3,1,2014-10-31,2014-10-30,0 days 12:30:00,before,FY2014Q3,2014-09-30
4,1,2015-02-18,2015-02-17,0 days 13:30:00,before,FY2014Q4,2014-12-31